stages:
  - build
  - deploy


build_app:
  stage: build
  image: cirrusci/flutter:latest
  script:
    - echo "Building Flutter web app..."
    - flutter build web --release --target=lib/main.dart
  artifacts:
    paths:
      - build/web/
  only:
    - master

deploy_app:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - echo "Deploying files to server..."
    - rsync -avz --delete build/web/ "$SERVER_USER@$SERVER_IP:$DEPLOY_PATH/"
    - echo "Deployment complete! ✅"
  only:
    - master