name: physio

packages:
  - packages/**

scripts:
  build:watch:
    description: Interactive build_runner watch with package selection
    run: dart scripts/build_runner_interactive.dart

  sync_dev_dependencies:
    run: dart scripts/sync_dev_dependencies.dart
    description: >
      Synchronize dev_dependencies from dev_dependencies.yaml 
      into the dev_dependencies section of all pubspec.yaml files 
      across the repository to ensure consistent development dependencies.

  sync_ui_dependencies:
    run: dart scripts/sync_ui_dependencies.dart
    description: "Add common dependencies to all feature packages"

  generate:l10n:
    run: flutter gen-l10n
    description: >
      Generate localization files using Flutter's localization tool
      to enable multi-language support throughout the app.

  generate:watch:
    run: |
      melos exec -c 1 --scope="domain,data,network" --depends-on="build_runner" -- "dart run build_runner watch --delete-conflicting-outputs"
    description: >
      Continuously watch and rebuild code generation outputs for domain, data, and network packages 
      using build_runner, ideal for development mode.

  generate:watch:feature:
    run: |
      echo "Enter the feature package name (e.g., search):"
      read feature
      melos exec -c 1 --scope="$feature" --depends-on="build_runner" -- "dart run build_runner watch --delete-conflicting-outputs"
    description: >
      Continuously watch and rebuild code generation outputs for a single feature package. 
      It will prompt for the feature name (e.g., search) and run on that package only.

  build:web:
    run: melos exec --scope="web_app" -- flutter build web --release

  generate_page:
    description: "Generate a new page structure. for run, use this command in target package 
    → dart run ../../../scripts/generate_page.dart search"
    run: |
      cd packages/features/\$1 && dart run ../../../scripts/generate_page.dart \$2