name: physio

packages:
  - packages/**

scripts:
  generate:build:
    run: dart scripts/build_single_package.dart
    description: Build runner for a single selected package interactively.

  sync_dev_dependencies:
    run: dart scripts/sync_dev_dependencies.dart
    description: >
      Synchronize dev_dependencies from dev_dependencies.yaml 
      into the dev_dependencies section of all pubspec.yaml files 
      across the repository to ensure consistent development dependencies.

  sync_ui_dependencies:
    run: dart scripts/sync_ui_dependencies.dart
    description: "Add common dependencies to all feature packages"

  generate:l10n:
    run: flutter gen-l10n
    description: >
      Generate localization files using Flutter's localization tool
      to enable multi-language support throughout the app.

  generate:watch:
    run: |
      melos exec -c 1 --depends-on="build_runner" -- "dart run build_runner watch --delete-conflicting-outputs"
    description: >
      Continuously watch and rebuild code generation outputs for packages 
      using build_runner, ideal for development mode.

  build:web:
    run: melos exec --scope="web_app" -- flutter build web --release