name: physio
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0


dependencies:
  login:
    path: packages/features/login

  register:
    path: packages/features/register

  forgot:
    path: packages/features/forgot

  main:
    path: packages/features/main

  splash:
    path: packages/features/splash

  verify:
    path: packages/features/verify

  utils:
    path: packages/core/utils

  ui:
    path: packages/core/ui

  network:
    path: packages/core/network

  domain:
    path: packages/domain

  data:
    path: packages/data

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.4
  intl: any
  get_it: ^8.0.3
  injectable: ^2.5.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  melos: ^6.3.2
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  responsive_framework: ^1.5.1

dev_dependencies:
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  test: ^1.25.15
  mocktail: ^1.0.4
  very_good_analysis: 6.0.0
  copy_with_extension_gen: ^6.0.0
  build_verify: ^3.1.0
  go_router_builder: ^2.9.0
  flutter_native_splash: ^2.4.6
  toastification: ^3.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
