name: ui
description: A package that contain shared ui in whole project.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

flutter:
  uses-material-design: true
  generate: true

dependencies:
  utils:
    path: ../utils

  domain:
    path: ../../domain

  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: any
  get_it: ^8.0.3
  injectable: ^2.5.0
  copy_with_extension: ^6.0.0
  responsive_framework: ^1.5.1
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  toastification: ^3.0.3
  flutter_svg: ^2.2.0

  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6

  chewie: ^1.12.1
  video_player: ^2.10.0

dev_dependencies:
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  test: ^1.25.15
  mocktail: ^1.0.4
  very_good_analysis: 6.0.0
  copy_with_extension_gen: ^6.0.0
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  go_router_builder: ^2.9.0
