name: splash
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0



dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../../domain
  utils:
    path: ../../core/utils
  ui:
    path: ../../core/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
