name: domain
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0


dependencies:
  utils:
    path: ../core/utils







dev_dependencies:
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  test: ^1.25.15
  mocktail: ^1.0.4
  very_good_analysis: 6.0.0
  copy_with_extension_gen: ^6.0.0
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  go_router_builder: ^2.9.0

